### ISSUE TITLE
2.8.3.7 This version will fail to compile.The previous version is normal

### ISSUE THREAD

**Issue by HuMzan** [tdlight-team/tdlight-java#103]
cannot access  it.tdlight.jni.TdApi

Bad class file:F:\Mvn\it\tdlight\tdlight-api-sealed\4.0.261\tdlight-api-sealed-4.0.261.jar(/it/tdlight/jni/TdApi.class)

Class file has wrong version 61.0, expecting 55.0
Please delete the file or ensure that the file is in the correct classpath subdirectory.

Version 2.8.3.2 will not have the above problems.

**Comment by HuMzan** [comment]
Using java17 is a little too radical

**Comment by cavallium** [comment]
Use java 17

**Comment by cavallium** [comment]
So you shouldn't use the sealed package. The normal version supports java 8+
