### ISSUE TITLE
Bot creating

### ISSUE THREAD

**Issue by yvasyliev** [tdlight-team/tdlight-java#11]
Hi!

Is it possible to use this library to create Telegram bot?
If so, could you please provide examples of bot creating and recieving/sending messages? 

Thanks!

**Comment by Cavallium** [comment]
Hi, I added an example implementation here:
https://github.com/tdlight-team/tdlight-java/tree/master/example

**Comment by yvasyliev** [comment]
Hi!

I mean do we have an opportunity to handle bot actions (the bot that was created by BotFather) with this library?
The example from your link is an implementation of Telegram Client.

I see that there is a [TdApi.CheckAuthenticationBotToken class](https://tdlight-team.github.io/tdlight-docs/it/tdlight/tdlib/TdApi.CheckAuthenticationBotToken.html) that is used in order to "log in as a bot".
So what are the next steps to recieve/send bot messages?

Thanks.

**Comment by Cavallium** [comment]
Just replace the phone number part with CheckAuthenticationBotToken and you are done
