### ISSUE TITLE
Getting Error "Too Many Requests" while trying to login

### ISSUE THREAD

**Issue by anandundavia** [tdlight-team/tdlight-java#115]
Whenever I try to login, I am getting the following error:

```java
Error {
  code = 429
  message = "Too Many Requests: retry after 64262"
}
```

I tried to search for the docs, but it seems like these errors are only for Telegram bots 
and it is only for sending messages. I did not come across any such errors for telegram clients.

The client that I am trying to run DOES NOT send _ANY_ messages to anyone.
In fact, there is no `client.send()` once the authentication flow ends.

Why do I have such an error?
How do I get around this?

Using these dependencies:
- tdlight-java-bom:2.8.4.3
- tdlight-java
- tdlight-natives-linux-amd64

**Comment by cavallium** [comment]
too many requests is not only for messages, it's for any type of request
