### ISSUE TITLE
exportchatinvitelink

### ISSUE THREAD

**Issue by NiotGG** [tdlight-team/tdlight-java#119]
The TdApi.ExportChatInviteLink dont exists.

https://core.telegram.org/bots/api/#exportchatinvitelink

**Comment by cavallium** [comment]
Tdlib is not bot api

**Comment by NiotGG** [comment]
I know, but how can I then get the invite link, when trying using TdApi.GetInviteLink method it says I don't have permission

**Comment by cavallium** [comment]
You should look at tdlib documentation, or ask in @tdlibchat
