### ISSUE TITLE
How to send text along with photo?

### ISSUE THREAD

**Issue by Serg95off** [tdlight-team/tdlight-java#124]
Please help!
I use this method to send a photo, how can I send text along with a photo?
I want the text to be under the photo

> TdApi.InputFile file = new TdApi.InputFileLocal("C:\\Users\\User\\Pictures\\1.JPG");
>         TdApi.InputMessageContent content = new TdApi.InputMessagePhoto(file,null,null, 300, 300, null,0);
>         client.send(new TdApi.SendMessage(id, 0, 0, null, null, content), chatIdResult -> {
>             // Get the chat response
>             var chat = chatIdResult.get();
>             // Print the message
>             System.out.printf("Received new message from chat %s: %s%n", id, text);
>         });

**Comment by cavallium** [comment]
You should set the caption
