### ISSUE TITLE
Type Long for phoneNumber not generally sufficient

### ISSUE THREAD

**Issue by Raffael-H** [tdlight-team/tdlight-java#134]
phoneNumber with type long is not applicable for all phone numbers. It would be better to choose a String or some other Type for it.

**Comment by cavallium** [comment]
It seems to be.
By the way, this is a limitation of tdlib, not of my wrapper, open an issue to tdlib.

**Comment by cavallium** [comment]
Wait, sorry, you are right, the bug is in my wrapper

**Comment by cavallium** [comment]
Fixed in https://github.com/tdlight-team/tdlight-java/releases/tag/v2.8.10.4
