### ISSUE TITLE
Will the user who will use the application based on TDLight have to install the TDLib library?

### ISSUE THREAD

**Issue by imyoric** [tdlight-team/tdlight-java#149]
Will the user who will use the application based on TDLight have to install the TDLib library?

**Comment by imyoric** [comment]
There is just a problem. The program worked for me, I sent it to the user, but nothing works for him.
![image](https://user-images.githubusercontent.com/63288807/230760671-ad94d94f-0b9a-4059-a8dc-00e1104d25a4.png)

**Comment by cavallium** [comment]
you didn't include the dependencies
