### ISSUE TITLE
Few moments to improve README

### ISSUE THREAD

**Issue by MadRatSRP** [tdlight-team/tdlight-java#151]
- I'm not sure if this is a bug a not, but still will describe it:

I installed tdlight-java

    implementation(platform("it.tdlight:tdlight-java-bom:2.8.10.6"))
    // do not specify the versions on the dependencies below!
    implementation("it.tdlight:tdlight-java")
    implementation("it.tdlight:tdlight-natives-windows-amd64")

and copied Example.java into my project

when i launched it console says:

SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.

if we need to do something about it i think it should be explained in README
- About [login] Do you want to login using a bot [token], a [phone] number, or a [qr] code? [token/phone/qr] line:

It would be cool if this would also be explained in README as newbee users such as myself doesnt know how to get bot token, the difference between regular bot token and userbot data and which should we use here

p.s. also if its possible to do it would be cool if the Example could just work without additional logging (dunno if there such a thing as testing accounts in telegram api or not)

**Comment by cavallium** [comment]
1. You didn't copy log4j.xml into your project's resources
2. I've changed the example file, now it uses the test telegram datacenter by default
3. I've updated the readme

**Comment by cavallium** [comment]
> > 1. You didn't copy log4j.xml into your project's resources
> > 2. I've changed the example file, now it uses the test telegram datacenter by default
> > 3. I've updated the readme
> 
> Thanks! It would be cool if log4j.xml stuff was mentioned in README.md, it would remove any questions and misunderstandings from the new users.

It's not needed because:
- The example should be cloned in its entirety if you are a newbie
- log4j2.xml is not related to my library itself, but with the logging library that I chose for the example.
