### ISSUE TITLE
GLIBC version

### ISSUE THREAD

**Issue by alon-sys** [tdlight-team/tdlight-java#152]
The GLIBC version requirements of the ssl version are too high, and the general server uses 2.34.
Can it be more flexible, dll/so can use self-built or default

**Comment by cavallium** [comment]
The new major release fixes this bug.

I've also added the following line to the Readme:

> If you want to use a different precompiled native, please set the java property it.tdlight.native.workdir. (Please note that you must build [this](https://github.com/tdlight-team/tdlight-java-natives), you can't put random precompiled tdlib binaries found on the internet)
