### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by ShafiqSadat** [tdlight-team/tdlight-java#16]
can you make a class like (https://github.com/rizaumami/tdbot.lua) it's for LUA 
and very easy to use and learn

**Comment by Cavallium** [comment]
This library is not meant to contain utilities or further abstractions, it's the most basic tdlib wrapper for java.
You can create a more easy to use library on top of tdlight-java.

**Comment by Cavallium** [comment]
By the way the class that you are looking for is: `it.tdlight.jni.TdApi`

**Comment by Cavallium** [comment]
https://tdlight-team.github.io/tdlight-docs/it/tdlight/tdlib/package-summary.html
