### ISSUE TITLE
Why does my dependency download fail

### ISSUE THREAD

**Issue by zybot666** [tdlight-team/tdlight-java#167]
![image](https://github.com/tdlight-team/tdlight-java/assets/125629395/8bab4924-bd7c-4c11-8bde-58ba0c90ddff)

**Comment by cavallium** [comment]
Try with the latest version

**Comment by zybot666** [comment]
I have probably fixed this issue, but when I went from local to linux, a new issue arose and I have filed a new issue, please help me
