### ISSUE TITLE
need tdjni.dll? And codes not include it 

### ISSUE THREAD

**Issue by lmcmceo** [tdlight-team/tdlight-java#17]
![image](https://user-images.githubusercontent.com/71498780/97803337-f227cf00-1c62-11eb-84a1-ad50a8104b93.png)
When I run example, it show exception, where is  tdjni.dll?

**Comment by Cavallium** [comment]
How are you importing tdlight into your project? Using maven or gradle?

**Comment by Cavallium** [comment]
Did you already fix it?
