### ISSUE TITLE
sendMessageAlbum not received update updateMessageSendSucceeded

### ISSUE THREAD

**Issue by viet0511** [tdlight-team/tdlight-java#173]
I'm trying to use `sendMessageAlbum` to send multiple photo groups, Messages are delivered but no `updateMessageSendSucceeded` was received so I can't know what is server message_id of those messages is.

I print all updates after sending those messages and only receive `UpdateNewMessage` and `UpdateChatLastMessage` but can't know what server message_id is from that.

If use the function `sendMessage` the `updateMessageSendSucceeded` is received normally.

I opened an issue on TDlLib and they confirmed sent messages by `sendMessageAlbum`  will be received [https://github.com/tdlib/td/issues/2595](https://github.com/tdlib/td/issues/2595)

So updates may be missing on [tdlight-java](https://github.com/tdlight-team/tdlight-java) side

Version: Lastest (tdlight-java-3.1.3+td.1.8.16, tdlight-natives-4.0.480-windows_amd64)

**Comment by cavallium** [comment]
tdlight java is just a tdlib wrapper, it's very improbable that this only happens with tdlight java.
Do you receive updateMessageSendSucceeded with other message types?

**Comment by viet0511** [comment]
I tried `sendMessage` the `updateMessageSendSucceeded` is received normally. 

The missing updates only happen if I using `sendMessageAlbum`

**Comment by viet0511** [comment]
I managed to resolve this, some of my code somehow blocked the update handler thread. I had removed and `updateMessageSendSucceeded` received normally
