### ISSUE TITLE
Cant download library classifier

### ISSUE THREAD

**Issue by ranjitsingha** [tdlight-team/tdlight-java#174]
Could not find it.tdlight:tdlight-natives:4.0.480.
     Required by:
         project :app
   > Could not find it.tdlight:tdlight-natives:4.0.480.
     Required by:
         project :app > it.tdlight:tdlight-java-bom:3.1.3+td.1.8.16

**Comment by cavallium** [comment]
Please, provide more details

**Comment by ranjitsingha** [comment]
i can't add the library with gradle. the above error occurs

**Comment by KurenaiRyu** [comment]
```
Could not determine the dependencies of task ':build'.
> Could not create task ':assemble'.
   > Could not create task ':jar'.
      > Could not resolve all files for configuration ':runtimeClasspath'.
         > Could not find it.tdlight:tdlight-natives:4.0.480.
           Searched in the following locations:
             - https://mvn.mchv.eu/repository/mchv/it/tdlight/tdlight-natives/4.0.480/tdlight-natives-4.0.480.pom
             - https://repo.maven.apache.org/maven2/it/tdlight/tdlight-natives/4.0.480/tdlight-natives-4.0.480.pom
             - https://dl.google.com/dl/android/maven2/it/tdlight/tdlight-natives/4.0.480/tdlight-natives-4.0.480.pom
           Required by:
               project :
         > Could not find it.tdlight:tdlight-natives:4.0.480.
           Searched in the following locations:
             - https://mvn.mchv.eu/repository/mchv/it/tdlight/tdlight-natives/4.0.480/tdlight-natives-4.0.480.pom
             - https://repo.maven.apache.org/maven2/it/tdlight/tdlight-natives/4.0.480/tdlight-natives-4.0.480.pom
             - https://dl.google.com/dl/android/maven2/it/tdlight/tdlight-natives/4.0.480/tdlight-natives-4.0.480.pom
           Required by:
               project : > it.tdlight:tdlight-java-bom:3.1.3+td.1.8.16
```

**Comment by cynthia2005** [comment]
Can you show me your Gradle build file?

**Comment by ghoshpukurcollegeapp** [comment]
> ```
> Could not determine the dependencies of task ':build'.
> > Could not create task ':assemble'.
>    > Could not create task ':jar'.
>       > Could not resolve all files for configuration ':runtimeClasspath'.
>          > Could not find it.tdlight:tdlight-natives:4.0.480.
>            Searched in the following locations:
>              - https://mvn.mchv.eu/repository/mchv/it/tdlight/tdlight-natives/4.0.480/tdlight-natives-4.0.480.pom
>              - https://repo.maven.apache.org/maven2/it/tdlight/tdlight-natives/4.0.480/tdlight-natives-4.0.480.pom
>              - https://dl.google.com/dl/android/maven2/it/tdlight/tdlight-natives/4.0.480/tdlight-natives-4.0.480.pom
>            Required by:
>                project :
>          > Could not find it.tdlight:tdlight-natives:4.0.480.
>            Searched in the following locations:
>              - https://mvn.mchv.eu/repository/mchv/it/tdlight/tdlight-natives/4.0.480/tdlight-natives-4.0.480.pom
>              - https://repo.maven.apache.org/maven2/it/tdlight/tdlight-natives/4.0.480/tdlight-natives-4.0.480.pom
>              - https://dl.google.com/dl/android/maven2/it/tdlight/tdlight-natives/4.0.480/tdlight-natives-4.0.480.pom
>            Required by:
>                project : > it.tdlight:tdlight-java-bom:3.1.3+td.1.8.16
> ```

my too same @cynthia2005

**Comment by KurenaiRyu** [comment]
```
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    application
    kotlin("jvm") version "1.9.10"
    kotlin("plugin.serialization") version "1.9.10"
    kotlin("plugin.lombok") version "1.9.10"
    id("io.freefair.lombok") version "5.3.0"
    id("org.graalvm.buildtools.native") version "0.9.20"
}

repositories {
    maven("https://mvn.mchv.eu/repository/mchv/") {
        content {
            includeGroup("it.tdlight")
        }
    }
    mavenCentral()
    google()
    mavenLocal {
        content {
            includeGroup("com.github.kurenairyu")
        }
    }
}
object Versions {
    ...
    const val tdlight = "3.1.3+td.1.8.16"
}
dependencies {
    ...
    //tdlib
    implementation(platform("it.tdlight:tdlight-java-bom:${Versions.tdlight}"))
    implementation("it.tdlight:tdlight-java")
    val hostOs = System.getProperty("os.name")
    val isWin = hostOs.startsWith("Windows")
    val classifier = when {
        hostOs == "Linux" -> "linux_amd64_gnu_ssl1"
        isWin -> "windows_amd64"
        else -> throw GradleException("[$hostOs] is not support!")
    }
    implementation(group = "it.tdlight", name = "tdlight-natives", classifier = classifier)
    //qrcode
    implementation("com.google.zxing:core:3.5.1")
    ...
}
```
My gradle build file

**Comment by cynthia2005** [comment]
> ```
> plugins {
>     application
>     kotlin("jvm") version "1.9.10"
>     kotlin("plugin.serialization") version "1.9.10"
>     kotlin("plugin.lombok") version "1.9.10"
>     id("io.freefair.lombok") version "5.3.0"
>     id("org.graalvm.buildtools.native") version "0.9.20"
> }
> 
> repositories {
>     maven("https://mvn.mchv.eu/repository/mchv/") {
>         content {
>             includeGroup("it.tdlight")
>         }
>     }
>     mavenCentral()
>     google()
> }
> object Versions {
>     ...
>     const val tdlight = "3.1.3+td.1.8.16"
> }
> dependencies {
>     ...
>     //tdlib
>     implementation(platform("it.tdlight:tdlight-java-bom:${Versions.tdlight}"))
>     implementation("it.tdlight:tdlight-java")
>     val hostOs = System.getProperty("os.name")
>     val isWin = hostOs.startsWith("Windows")
>     val classifier = when {
>         hostOs == "Linux" -> "linux_amd64_gnu_ssl1"
>         isWin -> "windows_amd64"
>         else -> throw GradleException("[$hostOs] is not support!")
>     }
>     implementation(group = "it.tdlight", name = "tdlight-natives", classifier = classifier)
>     //qrcode
>     implementation("com.google.zxing:core:3.5.1")
>     ...
> }
> ```
> 
> My gradle build file

Somehow your classifier is missing.

**Comment by akbcode** [comment]
```
plugins {
    kotlin("jvm") version "1.9.10"
    kotlin("plugin.serialization") version "1.9.10"
    application
}


repositories {
    mavenCentral()
    maven("https://mvn.mchv.eu/repository/mchv/")
    mavenLocal()
}


dependencies {
    implementation(platform("it.tdlight:tdlight-java-bom:3.1.3+td.1.8.16"))
    implementation("it.tdlight:tdlight-java")
    implementation(group = "it.tdlight", name = "tdlight-natives", classifier = "linux_arm64_gnu_ssl3")
    ...
}
```

Same error for me.
There is no .pom file at https://mvn.mchv.eu/#/mchv/it/tdlight/tdlight-natives/4.0.480
There is one in the 4.0.440 folder.

**Comment by cavallium** [comment]
> ```
> plugins {
>     kotlin("jvm") version "1.9.10"
>     kotlin("plugin.serialization") version "1.9.10"
>     application
> }
> 
> 
> repositories {
>     mavenCentral()
>     maven("https://mvn.mchv.eu/repository/mchv/")
>     mavenLocal()
> }
> 
> 
> dependencies {
>     implementation(platform("it.tdlight:tdlight-java-bom:3.1.3+td.1.8.16"))
>     implementation("it.tdlight:tdlight-java")
>     implementation(group = "it.tdlight", name = "tdlight-natives", classifier = "linux_arm64_gnu_ssl3")
>     ...
> }
> ```
> 
> Same error for me. There is no .pom file at https://mvn.mchv.eu/#/mchv/it/tdlight/tdlight-natives/4.0.480 There is one in the 4.0.440 folder.

Fixed, the file was missing

**Comment by cavallium** [comment]
> ```
> plugins {
>     application
>     kotlin("jvm") version "1.9.10"
>     kotlin("plugin.serialization") version "1.9.10"
>     kotlin("plugin.lombok") version "1.9.10"
>     id("io.freefair.lombok") version "5.3.0"
>     id("org.graalvm.buildtools.native") version "0.9.20"
> }
> 
> repositories {
>     maven("https://mvn.mchv.eu/repository/mchv/") {
>         content {
>             includeGroup("it.tdlight")
>         }
>     }
>     mavenCentral()
>     google()
> }
> object Versions {
>     ...
>     const val tdlight = "3.1.3+td.1.8.16"
> }
> dependencies {
>     ...
>     //tdlib
>     implementation(platform("it.tdlight:tdlight-java-bom:${Versions.tdlight}"))
>     implementation("it.tdlight:tdlight-java")
>     val hostOs = System.getProperty("os.name")
>     val isWin = hostOs.startsWith("Windows")
>     val classifier = when {
>         hostOs == "Linux" -> "linux_amd64_gnu_ssl1"
>         isWin -> "windows_amd64"
>         else -> throw GradleException("[$hostOs] is not support!")
>     }
>     implementation(group = "it.tdlight", name = "tdlight-natives", classifier = classifier)
>     //qrcode
>     implementation("com.google.zxing:core:3.5.1")
>     ...
> }
> ```
> 
> My gradle build file


Fixed, the file was missing

**Comment by cavallium** [comment]
> Could not find it.tdlight:tdlight-natives:4.0.480. Required by: project :app
> 
> > Could not find it.tdlight:tdlight-natives:4.0.480.
> > Required by:
> > project :app > it.tdlight:tdlight-java-bom:3.1.3+td.1.8.16


Fixed, the file was missing

**Comment by akbcode** [comment]
> 
> Fixed, the file was missing

I'm getting a different error

```
Execution failed for task ':compileKotlin'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not resolve it.tdlight:tdlight-natives:4.0.480.
     Required by:
         project :
      > Could not resolve it.tdlight:tdlight-natives:4.0.480.
         > inconsistent module metadata found. Descriptor: it.tdlight:tdlight-natives:4.0.440 Errors: bad version: expected='4.0.480' found='4.0.440'
   > Could not resolve it.tdlight:tdlight-natives:4.0.480.
     Required by:
         project : > it.tdlight:tdlight-java-bom:3.1.3+td.1.8.16
      > Could not resolve it.tdlight:tdlight-natives:4.0.480.
         > inconsistent module metadata found. Descriptor: it.tdlight:tdlight-natives:4.0.440 Errors: bad version: expected='4.0.480' found='4.0.440'
```
Need to update version number in pom file

**Comment by ghoshpukurcollegeapp** [comment]
> > Fixed, the file was missing
> 
> I'm getting a different error now
> 
> ```
> Execution failed for task ':compileKotlin'.
> > Could not resolve all files for configuration ':compileClasspath'.
>    > Could not resolve it.tdlight:tdlight-natives:4.0.480.
>      Required by:
>          project :
>       > Could not resolve it.tdlight:tdlight-natives:4.0.480.
>          > inconsistent module metadata found. Descriptor: it.tdlight:tdlight-natives:4.0.440 Errors: bad version: expected='4.0.480' found='4.0.440'
>    > Could not resolve it.tdlight:tdlight-natives:4.0.480.
>      Required by:
>          project : > it.tdlight:tdlight-java-bom:3.1.3+td.1.8.16
>       > Could not resolve it.tdlight:tdlight-natives:4.0.480.
>          > inconsistent module metadata found. Descriptor: it.tdlight:tdlight-natives:4.0.440 Errors: bad version: expected='4.0.480' found='4.0.440'
> ```
> 
> Need to update version number in pom file

exactly same error i am getting

**Comment by cavallium** [comment]
Done, I updated the file. If you still get the error, delete the folder it/tdlight in your .m2 folder
