### ISSUE TITLE
UpdateChatMember update doesn't get fired

### ISSUE THREAD

**Issue by GhOsTSt3p** [tdlight-team/tdlight-java#175]
I've tried using **UpdateChatMember** to detect when a player leaves a channel and I'm pretty sure that's the correct update I need.

**Handler Registration**
```java
clientBuilder.addUpdateHandler(TdApi.UpdateChatMember.class, Main::onUpdateChatMember);
``` 

**Handler Method**
```java
private static void onUpdateChatMember(TdApi.UpdateChatMember update) {
    System.out.println("Hi, this is a debug method!");
}
``` 

The client connection works fine, other updates such as **UpdateNewMessage** prints properly any messages received.

**Comment by cavallium** [comment]
UpdateChatMember does not get sent reliably, Telegram does not send this information sometimes. You should ask api-related questions in t.me/tdlib_chat
