### ISSUE TITLE
Cant setup

### ISSUE THREAD

**Issue by ghoshpukurcollegeapp** [tdlight-team/tdlight-java#177]
dependencies {

    
    implementation platform('it.tdlight:tdlight-java-bom:3.1.4+td.1.8.17')
    implementation group: 'it.tdlight', name: 'tdlight-java'
    implementation group: 'it.tdlight', name: 'tdlight-natives', classifier: 'linux_arm64_clang_ssl3'
}

What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class it.tdlight.jni.TdApi found in modules tdlight-api-4.0-legacy.452-legacy (it.tdlight:tdlight-api:4.0.452) and tdlight-api-4.0.452 (it.tdlight:tdlight-api:4.0.452)
     Duplicate class it.tdlight.jni.TdApi$AcceptCall found in modules tdlight-api-4.0-legacy.452-legacy (it.tdlight:tdlight-api:4.0.452) and tdlight-api-4.0.452 (it.tdlight:tdlight-api:4.0.452)
     Duplicate class it.tdlight.jni.TdApi$AcceptTermsOfService found in modules tdlight-api-4.0-legacy.452-legacy (it.tdlight:tdlight-api:4.0.452) and tdlight-api-4.0.452 (it.tdlight:tdlight-api:4.0.452)
     Duplicate class it.tdlight.jni.TdApi$AccessHash found in modules tdlight-api-4.0-legacy.452-legacy (it.tdlight:tdlight-api:4.0.452) and tdlight-api-4.0.452 (it.tdlight:tdlight-api:4.0.452)
     Duplicate class it.tdlight.jni.TdApi$AccessHashType found in modules tdlight-api-4.0-legacy.452-legacy (it.tdlight:tdlight-api:4.0.452) and tdlight-api-4.0.452 (it.tdlight:tdlight-api:4.0.452)
     Duplicate class it.tdlight.jni.TdApi$AccessHashTypeChannel found in modules tdlight-api-4.0-legacy.452-legacy (it.tdlight:tdlight-api:4.0.452) and tdlight-api-4.0.452 (it.tdlight:tdlight-api:4.0.452)
     Duplicate class it.tdlight.jni.TdApi$AccessHashTypeUser found in modules tdlight-api-4.0-legacy.452-legacy (it.tdlight:tdlight-api:4.0.452) and tdlight-api-4.0.452 (it.tdlight:tdlight-api:4.0.452)

**Comment by cavallium** [comment]
Android is currently not supported: #29
