### ISSUE TITLE
ResponseReceiver.run High CPU time

### ISSUE THREAD

**Issue by mircoianese** [tdlight-team/tdlight-java#178]
Hello, 

I was profiling my Java application (which does some CPU-intense tasks) and I noticed a very high CPU time usage by tdlight, particularly by the ResponseReceiver run method:
![image](https://github.com/tdlight-team/tdlight-java/assets/22716366/5817c9f1-d120-41a2-b0f7-d84835dd150c)

I'm running on Java 17 using the `linux_amd64_gnu_ssl3` package.
Not sure if this is correct, but it seems to me that the thread is looping maybe "too fast" and causing this behavior (the previous screenshot was taken exactly after 40 seconds of profiling).

Is this expected?
Thanks!

**Comment by cavallium** [comment]
Please, enable async profiling and native cpu profiling, you will see the real tdlib cpu usage of that method
