### ISSUE TITLE
How to download a file asynchorously?

### ISSUE THREAD

**Issue by Dhina17** [tdlight-team/tdlight-java#19]
`downloadFile.synchronous = false`   I have assign it to false for this field but still I can't receive updates through result handler more than one time. I receive the updates only one time after the download has been started. It will be helpful if someone tells my mistake.

`DownloadFile downloadFile = new DownloadFile();
downloadFile.fileId = remoteFileId;
downloadFile.offset = 0;
downloadFile.limit = 0;
downloadFile.synchronous = false;
downloadFile.priority = 1;
Client.client.send(downloadFile, new ResultHandler(){

      @Override
      public void onResult(Object object) {
         System.out.println(object); // It runs only for the first time
         UpdateFile updateFile = (UpdateFile) object;
         System.out.println("Downloaded: "+ updateFile.file.local.downloadedSize); // It didn't run ever
         if(updateFile.file.local.isDownloadingCompleted) // It didn''t run ever
           System.out.println("File downloaded"); 
      }
            
});`

**Note: File downloaded fine, But I can't receive the update**

**Comment by Cavallium** [comment]
You are listening the result of your request, but you must also listen for the global updates of type UpdateFile.

**Comment by Dhina17** [comment]
Yep I need to handle that through UpdatesHandler of the client. Thank you
