### ISSUE TITLE
TdApi.JoinChatByInviteLink return it.tdlight.client.TelegramError: 500: Internal Server Error: failed to join chat via invite link

### ISSUE THREAD

**Issue by tzxyz** [tdlight-team/tdlight-java#199]
I encountered an exception when using the TdApi.JoinChatByInviteLink API to join a group, but it successfully joined the group in the Telegram app.

Log:
```
2023-12-13 02:31:44.890 ERROR 32928 --- [       Thread-5] it.tdlight.TDLight                       : [ 1][t 5][1702405904.891502618][ContactsManager.cpp:2910][#1][!Td]	Receive wrong result for ImportChatInviteQuery
```

**Comment by JavoxirJava** [comment]
I can't use it, can you help me, I just started learning this and I can't even find a video tutorial

**Comment by cavallium** [comment]
Can you try with the latest version?

**Comment by dmb72** [comment]
Hmm sorry. I'm use original tdlib and c# with same result.
