### ISSUE TITLE
it.tdlight:tdlght-api sources

### ISSUE THREAD

**Issue by miraclefoxx** [tdlight-team/tdlight-java#20]
Where do I find the sources for said module? 
IntelliJ Idea maven plugin fails to load them and I can't find them manually in the repos either

**Comment by Cavallium** [comment]
I'm publishing the sources with the next release, today

**Comment by Cavallium** [comment]
Fixed, update to the latest version.

**Comment by miraclefoxx** [comment]
Works like a charm.
As a sidenote, TdApi.java is _gigantic_ file (3.4 MB) and IDEA doesn't even attempt to index it without properties tweak 
`idea.max.intellisense.filesize=4096`
However, this noticeably slows down the IDE.
I don't know if this is the case with Eclipse or such, but splitting the file down would help a ton.

**Comment by Cavallium** [comment]
@miraclefoxx This is a problem of the original TDLib. That file is not generated by me.I only add some functions to it.
