### ISSUE TITLE
UpdateMessageEdited Cannot receive callback of robot edited message

### ISSUE THREAD

**Issue by msxfXF** [tdlight-team/tdlight-java#201]
`clientBuilder.addUpdateHandler(TdApi.UpdateMessageEdited.class, this::onUpdateMessageEdit);
`
The callback of the user editing message can be accepted normally.
But Cannot receive callback of robot editor message.

**Comment by cavallium** [comment]
This is a tdlib question, you should ask to the tdlib developers
