### ISSUE TITLE
Is there any plans to add support for similar channels feature?

### ISSUE THREAD

**Issue by Sammers21** [tdlight-team/tdlight-java#202]
I guess you have to update the tdlib version the newer version

**Comment by Sammers21** [comment]
![image](https://github.com/tdlight-team/tdlight-java/assets/16746106/f4f10d85-39f1-4a5c-80b9-b9782f76eb91)

**Comment by Sammers21** [comment]
![image](https://github.com/tdlight-team/tdlight-java/assets/16746106/d4ae4d65-b1aa-48e6-8249-d0150410596e)

**Comment by cavallium** [comment]
Done
