### ISSUE TITLE
cannot receive the messages from channel

### ISSUE THREAD

**Issue by fc6666666** [tdlight-team/tdlight-java#215]
Hi Team

current we are having problems receiving channel messages ...

our setup:
1, using example code: https://github.com/tdlight-team/tdlight-java/blob/master/example/src/main/java/it/tdlight/example/Example.java

2, we have two active sessions in telegram, one is using telegram desktop mac, the other is the session using tdlight

3, desktop app could always receive/show all updates from one telegram channel, while the tdlight session seemed stucked with only very few of these updates.

4, however tdlight session could always receive direct messages on time.

any ideas where we could check?

**Comment by cavallium** [comment]
Please check if you are blocking the tdlib thread
