### ISSUE TITLE
 https://mvn.mchv.eu/repository/mchv  is 404

### ISSUE THREAD

**Issue by MrKangZuBin** [tdlight-team/tdlight-java#225]
:im-service:main: Could not find it.tdlight:tdlight-java-bom:v3.4.0+td.1.8.26.
Searched in the following locations:
  - https://repo.maven.apache.org/maven2/it/tdlight/tdlight-java-bom/v3.4.0+td.1.8.26/tdlight-java-bom-v3.4.0+td.1.8.26.pom
  - https://mvn.mchv.eu/repository/mchv/it/tdlight/tdlight-java-bom/v3.4.0+td.1.8.26/tdlight-java-bom-v3.4.0+td.1.8.26.pom
Required by:
    project :im-service

**Comment by cavallium** [comment]
You added a 'v' before the version. Remove that.

It's "3.4.0+td.1.8.26"

**Comment by MrKangZuBin** [comment]
:im-service:main: Could not find it.tdlight:tdlight-java-bom:3.4.0+td.1.8.26.
Required by:
    project :im-service > project :user-service  一样的

**Comment by MrKangZuBin** [comment]
is ok

**Comment by cavallium** [comment]
Did you add the mchv repository?

**Comment by MrKangZuBin** [comment]
yes
