### ISSUE TITLE
Fix chats printing in the Example.java

### ISSUE THREAD

**Issue by CaliforniaMountainSnake** [tdlight-team/tdlight-java#23]
https://github.com/tdlight-team/tdlight-java/blob/aab1177b3437fddb4343e48829a3177dd28b0027/example/src/main/java/it.tdlight.example/Example.java#L284

If you set the `limit` bigger than the count of your chats, then you will give NotSuchElement exception.

The fix:
```java
for (int i = 0; i < mainChatList.size() && i < limit; i++) {
```

**Comment by andrew-ld** [comment]
the example was taken from the original tdlib repo, you should report on https://github.com/tdlib/td

**Comment by andrew-ld** [comment]
https://github.com/tdlib/td/blob/27d3fdd09d90f6b77ecbcce50b1e86dc4b3dd366/example/java/org/drinkless/tdlib/example/Example.java#L288

**Comment by CaliforniaMountainSnake** [comment]
> the example was taken from the original tdlib repo, you should report on https://github.com/tdlib/td

Thanks: https://github.com/tdlib/td/issues/1372

**Comment by Cavallium** [comment]
I'm closing the issue, since there's the issue in td repository
