### ISSUE TITLE
Unable to load Maven meta-data from https://mvn.mchv.eu/repository/mchv/it/tdlight/tdlight-java/maven-metadata.xml

### ISSUE THREAD

**Issue by CaliforniaMountainSnake** [tdlight-team/tdlight-java#24]
I just can't download TDLight dependency.
It looks like a very strange bug.

This URLs:
>https://mvn.mchv.eu/repository/mchv/it/tdlight/tdlight-java/maven-metadata.xml
>http://mvn.mchv.eu/repository/mchv/it/tdlight/tdlight-java/maven-metadata.xml

are really not accessible at this moment.
I already tried using another internet connection and TOR browser, but the result is the same.

The build completed normally a few days ago with exactly the same `build.gradle`.

![Screenshot_20210120_180311](https://user-images.githubusercontent.com/44233829/105193941-22885680-5b4a-11eb-9f61-c347e94241c4.png)

**Comment by andrew-ld** [comment]
currently the maven server is offline, the cluster sysadmin is solving the problem now

**Comment by Cavallium** [comment]
Fixed

**Comment by CaliforniaMountainSnake** [comment]
![Screenshot_20210122_151046](https://user-images.githubusercontent.com/44233829/105489270-07415680-5cc4-11eb-8318-635ea28a238e.png)

**Comment by Cavallium** [comment]
Fixed again. Sorry but we changed the isp recently.

**Comment by Dhina17** [comment]
same error again

**Comment by CaliforniaMountainSnake** [comment]
Yes, this happens again...

**Comment by Dhina17** [comment]
Now works fine

**Comment by CaliforniaMountainSnake** [comment]
Hello, your maven server has fallen again...
https://github.com/tdlight-team/tdlight/issues/21

**Comment by Cavallium** [comment]
Sorry I know it's down but I'm at work now

**Comment by Cavallium** [comment]
Fixed

**Comment by CaliforniaMountainSnake** [comment]
@Cavallium Hello, it happened again...
https://mvn.mchv.eu/repository/mchv/it/tdlight/tdlight-java/3.171.43/tdlight-java-3.171.43.pom
![Screenshot_20210729_131352](https://user-images.githubusercontent.com/44233829/127474609-432b5811-ddd5-4ad9-ad47-c19544025c18.png)

**Comment by Cavallium** [comment]
You must update to the latest version because I changed the versioning of the library, and the old packages were seen as newer by maven.

**Comment by Cavallium** [comment]
https://github.com/tdlight-team/tdlight-java/releases/tag/v1.7.6.0

**Comment by CaliforniaMountainSnake** [comment]
> You must update to the latest version because I changed the versioning of the library

@Cavallium This was a very bad idea, man. Many people don't need the latest version. This is the reason why we use package managers - to be sure we always use the same dependency version.

I can't build the project even with the latest version:
https://mvn.mchv.eu/repository/mchv/it/tdlight/tdlight-java/1.7.6.0/tdlight-java-1.7.6.0.pom
```
repositories {
     maven { url "https://mvn.mchv.eu/repository/mchv/" }
}
dependencies {
     implementation 'it.tdlight:tdlight-java:1.7.6.0'
     implementation 'it.tdlight:tdlight-natives-linux-amd64:3.3.58'
}
```

![Screenshot_20210729_132743](https://user-images.githubusercontent.com/44233829/127476837-0e4816d6-0f5b-4728-b630-5b6d4514806c.png)

**Comment by Cavallium** [comment]
I know but the old versioning format broke maven version ranges.

By the way the latest version is 1.7.6.1

**Comment by CaliforniaMountainSnake** [comment]
> By the way the latest version is 1.7.6.1

Ok, thanks, I now can build the project with the following versions:
```
implementation 'it.tdlight:tdlight-java:1.7.6.1'
implementation 'it.tdlight:tdlight-natives-linux-amd64:3.3.58'
```
