### ISSUE TITLE
Error: Receive is called after Client destroy, or simultaneously from different threads

### ISSUE THREAD

**Issue by CaliforniaMountainSnake** [tdlight-team/tdlight-java#25]
I want to create a multi-threaded system that uses TDLib.
I wrote a Runnable class where I create a tdlib client and set an updates handler.
Each thread has its own TelegramClient and its own updates handler. Each class manages its own telegram account.

If I run only 1 thread, all works good, but if I run 2 or more threads, I got this error after the second TelegramClient was created:

`[ 0][t 0][1612181768.710582017][Client.cpp:279] Receive is called after Client destroy, or simultaneously from different threads`

I should use 1 global updates handler for all clients?

Probably this issue is tied to this one: https://github.com/tdlib/td/issues/1242

**Comment by Cavallium** [comment]
@CaliforniaMountainSnake No probably you are doing something wrong. Handling multiple clients on different threads is not a problem in tdlight

**Comment by CaliforniaMountainSnake** [comment]
It fixed this!

My code before:
```java
  private TelegramClient createTelegramClient(UniversalHandler defaultHandler) {
        TelegramClient client = ClientManager.create(defaultHandler.getUpdateHandler(),
                defaultHandler.getUpdateExceptionHandler(), defaultHandler.getDefaultExceptionHandler());
        return client;
    }
```

My code after:
```java
  private static synchronized TelegramClient createTelegramClient(UniversalHandler defaultHandler) {
        TelegramClient client = ClientManager.create(defaultHandler.getUpdateHandler(),
                defaultHandler.getUpdateExceptionHandler(), defaultHandler.getDefaultExceptionHandler());
        return client;
    }
```

@Cavallium, maybe you should make ClientManager::create() method synchronized by default? It is static anyway.

**Comment by CaliforniaMountainSnake** [comment]
> @CaliforniaMountainSnake No probably you are doing something wrong. Handling multiple clients on different threads is not a problem in tdlight

The problem is definitely tied with the client's creation.

**Comment by CaliforniaMountainSnake** [comment]
So, you can't create multiple telegram clients at the same time. You can't start creating a new client until the previous client is still being created.

**Comment by Cavallium** [comment]
In the latest release it's fixed
