### ISSUE TITLE
Initialization error: Can't find field [thumbnail] with signature [Lit/ernytech/tdlib/TdApi$PhotoSize;]

### ISSUE THREAD

**Issue by dariocode** [tdlight-team/tdlight-java#3]
I'm trying to Create a client, but during the init.start method of the tdjni.dll windows library it throw the follow exception:

> [ 1][t 0][1597330087.925651312][tl_jni_object.cpp:36]	Can't find field [thumbnail] with signature > [Lit/ernytech/tdlib/TdApi$PhotoSize;]

> Fatal error: Can't find field [thumbnail] with signature [Lit/ernytech/tdlib/TdApi$PhotoSize;]

I'm using tdlib version 2.167.10

**Comment by dariocode** [comment]
looking for a solution I found a similar issue at https://github.com/tdlib/td/issues/992
The problem maybe the same
"It seems that you are using different TDLib versions simultaneously in different places."

**Comment by Cavallium** [comment]
Yes that's the same issue, you must use this wrapper only with the same version of TDLib.
If you use the version 2.167.10 it means that you must use TDLib 1.6.7.

**Comment by Cavallium** [comment]
I'm working to update the windows binaries included in tdlight.

**Comment by Cavallium** [comment]
I fixed it in the latest release, 3.168.0.
I updated the README with the instructions to add TDLight to your project.
Note that i changed the package name from `it.ernytech.tdlib` to `it.tdlight.tdlight`, and the maven package to
groupId: `it.tdlight`
artifactId: `tdlight-java`
