### ISSUE TITLE
[Question] No update handler for error

### ISSUE THREAD

**Issue by vellrya** [tdlight-team/tdlight-java#31]
Hello.

I successfully initialize client and then call:

`        client.send(TdApi.GetStickerSet(123456L), { println("Test: "+it) }, { println("Exception: "+it) })`

Assuming that id is invalid and I want to get error (in update handler with "Test: " I guess), but I didn't get any response. Neither in update nor in error, 
Is this expected behavior? If I set log level to 3, then in debug output I see:
```
[ 3][t 5][1618056339.245123624][NetQuery.h:322][#1][!Session:3:main][&net_query]	Got error [Query:[id:589824][tl:0x2619a90e][state:Query]] [Error : 400 : STICKERSET_INVALID]
[ 3][t 5][1618056339.245144367][NetQuery.h:244][#1][!Session:3:main][&net_query]	[Query:[id:589824][tl:0x2619a90e][state:Error][Error : 400 : STICKERSET_INVALID]] [state:sent to callback]
[ 3][t 5][1618056339.245156049][NetQuery.h:244][#1][!Td][&net_query]	[Query:[id:589824][tl:0x2619a90e][state:Error][Error : 400 : STICKERSET_INVALID]] [state:Td: received from DcManager]
[ 3][t 5][1618056339.245162010][Td.cpp:3533][#1][!Td][&net_query]	Receive result of [Query:[id:589824][tl:0x2619a90e][state:Error][Error : 400 : STICKERSET_INVALID]]
[ 3][t 5][1618056339.245182037][StickersManager.cpp:696][#1][!Td]	Receive error for GetStickerSetQuery: [Error : 400 : STICKERSET_INVALID]
```
but no response in callback. Can you please check?
Thanks)

Dependency version:  
tdlight-java:4.171.87
tdlight-natives-windows-amd64:3.3.17

**Comment by Cavallium** [comment]
@vellrya Looking at the logs the response has been sent to the error callback successfully. check if your code works correctly.

**Comment by vellrya** [comment]
I see message in the logs too, but all code for reproducing provided in this line. (123456 - it is example incorrect sticker set id, I don't change it):

client.send(TdApi.GetStickerSet(123456L), { println("Test: "+it) }, { println("Exception: "+it) })

I don't see any output in console. If I provide correct setId, then response appeared in update callback.
I should see "Test: ..." output in console, shouldn't I?

**Comment by Cavallium** [comment]
Can you try printing the output with System.out.println?

**Comment by Cavallium** [comment]
If it isn't working, can you try if also other methods have this problem, like TdApi.GetUser(-1)?

**Comment by vellrya** [comment]
Alrady)

```
        Thread.sleep(2000)
        client.send(TdApi.GetStickerSet(123456L), { System.out.println("Test1: "+it) }, { System.out.println("Exception1: "+it) })
        Thread.sleep(5000)
        client.send(TdApi.GetUserFullInfo(123456), { System.out.println("Test2: "+it) }, {System.out.println("Exception2: "+it)})
        Thread.sleep(5000)
```

Output:

> [ 3][t 3][1618146996.561602830][MessagesManager.cpp:14571][#1][!net_actor]	Receive 0 chats out of 0 in folder 1
> [ 3][t 3][1618146996.561622142][MessagesManager.cpp:35084][#1][!net_actor]	Update last dialog date in folder 1 from [9221294780217032704, 0] to [0, 0]
> [ 3][t 3][1618146996.561635494][MessagesManager.cpp:35086][#1][!net_actor]	Know about 0 chats
> [ 3][t 3][1618146996.561652421][MessagesManager.cpp:35157][#1][!net_actor]	Update last dialog date in chat list folder 1 from [9221294780217032704, 0] to [0, 0]
> [ 3][t 3][1618146996.561670541][MessagesManager.cpp:9451][#1][!net_actor]	Inited total chat count in chat list folder 1
> [ 3][t 3][1618146996.976097583][StateManager.cpp:146][#1][!State manager]	Auto set net_type = Other
> [ 3][t 3][1618146996.976189374][ConnectionCreator.cpp:549][#1][!ConnectionCreator][&connections]	Receive network flag true with generation 1
> [ 3][t 3][1618146996.976205825][ConnectionCreator.cpp:554][#1][!ConnectionCreator][&connections]	Set proxy query token to 0: 1 1
> [ 3][t 3][1618146996.976219415][ConnectionCreator.cpp:844][#1][!ConnectionCreator][&connections]	In client_loop: [client:0x55f7a870d8314d59]
> [ 3][t 3][1618146996.976235389][ConfigManager.cpp:763][#1][!Recoverer][&config_recoverer]	Successfully connected in 0.997750
> [ 3][t 3][1618146996.976268053][ConfigManager.cpp:837][#1][!Recoverer][&config_recoverer]	Wakeup never
> [ 3][t 0][1618146998.561832189][Client.cpp:284][&td_requests]	End to wait for updates, returning object 0 0000000000000000
> [ 3][t 0][1618146998.561865091][Client.cpp:276][&td_requests]	Begin to wait for updates with timeout 2.000000
> [ 3][t 3][1618146999.147153615][Td.cpp:3368][#1][!Td][&td_requests]	Receive request 6: GetStickerSet {
>   setId = 123456
> }
> [ 3][t 3][1618146999.147233963][StickersManager.cpp:3648][#1][!GetStickerSetRequest]	Trying to load sticker set 0 with stickers from server
> [ 3][t 3][1618146999.147262811][StickersManager.cpp:668][#1][!GetStickerSetRequest]	Load sticker set 0 from server: inputStickerSetID {
>   id = 0
>   access_hash = 0
> }
> [ 3][t 3][1618146999.147279977][NetQuery.h:360][#1][!GetStickerSetRequest]	[Query:[id:589824][tl:0x2619a90e][state:Query]]
> [ 3][t 3][1618146999.147291898][Td.cpp:3525][#1][!GetStickerSetRequest][&net_query]	Send [Query:[id:589824][tl:0x2619a90e][state:Query]] to dispatcher
> [ 3][t 3][1618146999.147297620][NetQuery.h:244][#1][!GetStickerSetRequest][&net_query]	[Query:[id:589824][tl:0x2619a90e][state:Query]] [state:Td: send to NetQueryDispatcher]
> [ 3][t 3][1618146999.147308826][NetQuery.h:244][#1][!GetStickerSetRequest][&net_query]	[Query:[id:589824][tl:0x2619a90e][state:Query]] [state:sent to main session multi proxy DcId{3}]
> [ 3][t 3][1618146999.147325277][NetQuery.h:244][#1][!SessionProxy:3:main][&net_query]	[Query:[id:589824][tl:0x2619a90e][state:Query]] [state:SessionProxy:3:main: sent to session]
> [ 3][t 3][1618146999.147331237][Session.cpp:258][#1][!Session:3:main][&net_query]	Got query [Query:[id:589824][tl:0x2619a90e][state:Query]]
> [ 3][t 3][1618146999.147336244][NetQuery.h:244][#1][!Session:3:main][&net_query]	[Query:[id:589824][tl:0x2619a90e][state:Query]] [state:Session: pending]
> [ 3][t 3][1618146999.147346258][NetQuery.h:244][#1][!Session:3:main][&net_query]	[Query:[id:589824][tl:0x2619a90e][state:Query]] [state:Session: trying to send to mtproto::connection]
> [ 3][t 3][1618146999.147354125][Session.cpp:967][#1][!Session:3:main][&net_query]	Send query to connection [Query:[id:589824][tl:0x2619a90e][state:Query]] [msg_id:0x6072f6b6cdcb7e1c][invoke_after:0x0000000000000000]
> [ 3][t 3][1618146999.341157674][Session.cpp:806][#1][!Session:3:main][&net_query]	Return query error [Query:[id:589824][tl:0x2619a90e][state:Query]]
> [ 3][t 3][1618146999.341196060][NetQuery.h:322][#1][!Session:3:main][&net_query]	Got error [Query:[id:589824][tl:0x2619a90e][state:Query]] [Error : 400 : STICKERSET_INVALID]
> [ 3][t 3][1618146999.341245651][NetQuery.h:244][#1][!Session:3:main][&net_query]	[Query:[id:589824][tl:0x2619a90e][state:Error][Error : 400 : STICKERSET_INVALID]] [state:sent to callback]
> [ 3][t 3][1618146999.341263055][NetQuery.h:244][#1][!Td][&net_query]	[Query:[id:589824][tl:0x2619a90e][state:Error][Error : 400 : STICKERSET_INVALID]] [state:Td: received from DcManager]
> [ 3][t 3][1618146999.341270923][Td.cpp:3533][#1][!Td][&net_query]	Receive result of [Query:[id:589824][tl:0x2619a90e][state:Error][Error : 400 : STICKERSET_INVALID]]
> [ 3][t 3][1618146999.341301202][StickersManager.cpp:696][#1][!Td]	Receive error for GetStickerSetQuery: [Error : 400 : STICKERSET_INVALID]
> [ 3][t 0][1618147000.562551498][Client.cpp:284][&td_requests]	End to wait for updates, returning object 0 0000000000000000
> [ 3][t 0][1618147000.562601327][Client.cpp:276][&td_requests]	Begin to wait for updates with timeout 2.000000
> [ 3][t 0][1618147002.562818288][Client.cpp:284][&td_requests]	End to wait for updates, returning object 0 0000000000000000
> [ 3][t 0][1618147002.562866449][Client.cpp:276][&td_requests]	Begin to wait for updates with timeout 2.000000
> [ 3][t 3][1618147004.149793386][Td.cpp:3368][#1][!Td][&td_requests]	Receive request 7: GetUserFullInfo {
>   userId = 123456
> }
> [ 3][t 3][1618147004.149828672][RequestActor.h:111][#1][!GetUserFullInfoRequest]	Receive error for query: [Error : 6 : User not found]
> [ 3][t 3][1618147004.149834871][Td.cpp:4573][#1][!Td][&td_requests]	Sending error for request 7: Error { code = 6 message = "User not found" }
> [ 3][t 0][1618147004.149861574][Client.cpp:284][&td_requests]	End to wait for updates, returning object 7 0000000023F28D50
> [ 3][t 0][1618147004.149888515][Client.cpp:276][&td_requests]	Begin to wait for updates with timeout 0.000000
> [ 3][t 0][1618147004.149904966][Client.cpp:284][&td_requests]	End to wait for updates, returning object 0 0000000000000000
> [ 3][t 0][1618147004.150064468][Client.cpp:276][&td_requests]	Begin to wait for updates with timeout 2.000000
> Test2: Error {
>   code = 6
>   message = "User not found"
> }

Test2 callback called, Test1 or Exception1 callback doesn't call.

**Comment by Cavallium** [comment]
This seems a bug in the native part of the library.

If you are using the package "tdlight-java" the bug can be related to tdlight itself and you must report it to me.
If you are using the package "tdlib-java" the bug is related to tdlib, so you must report it to tdlib/td repository.

**Comment by vellrya** [comment]
Now I use only tdlight:

>         <dependency>
>             <groupId>it.tdlight</groupId>
>             <artifactId>tdlight-java</artifactId>
>             <version>4.171.87</version>
>         </dependency>
>         <dependency>
>             <groupId>it.tdlight</groupId>
>             <artifactId>tdlight-natives-windows-amd64</artifactId>
>             <version>3.3.17</version>
>         </dependency>

**Comment by vellrya** [comment]
And one more small question: how can I use tdlight options in java wrapper, such as ignore_server_deletes_and_reads?

Unfortuanely, I can't find any example with this option in repository.

**Comment by Cavallium** [comment]
No, if you want you can just ignore them
