### ISSUE TITLE
Can't find class [it/tdlight/jni/TdApi$BotInfo]

### ISSUE THREAD

**Issue by hades12x1** [tdlight-team/tdlight-java#35]
Using the following dependency and the example program
repositories {
    mavenCentral()
    maven { url "https://mvn.mchv.eu/repository/mchv/" }
}

dependencies {
    implementation 'it.tdlight:tdlight-java:4.171.126'
    implementation 'it.tdlight:tdlight-natives-windows-amd64:3.3.51'
}

I test the example on Windows 10, But there is error:
```
[ 1][t 0][1625280421.779124259][tl_jni_object.cpp:39]	Can't find class [it/tdlight/jni/TdApi$BotInfo]
```
Please help me. 
Thanks!

**Comment by Cavallium** [comment]
@hades12x1 dependencies { 
    implementation 'it.tdlight:tdlight-java:4.171.128' 
    implementation 'it.tdlight:tdlight-natives-windows-amd64:3.3.55' 
}

**Comment by Cavallium** [comment]
Also try to recompile the project, maybe it has cached the old version of tdapi.java

**Comment by hades12x1** [comment]
> Also try to recompile the project, maybe it has cached the old version of tdapi.java

Ok. I try it.
Thank you.!
