### ISSUE TITLE
UnsatisfiedLinkError: 'TdApi$Object.toString()'

### ISSUE THREAD

**Issue by demkom58** [tdlight-team/tdlight-java#39]
When calls toString() on TdApi.Object, an UnsatisfiedLinkError occurs. Simple code to reproduce:

```
TdApi.TdlibParameters parameters = new TdApi.TdlibParameters();
System.out.println(parameters);
```

An error occurred:

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: 'java.lang.String it.tdlight.jni.TdApi$Object.toString()'
	at it.tdlight.jni.TdApi$Object.toString(Native Method)
	at com.demkom58.testgram.Main.main(Main.java:9)
```

**Comment by Cavallium** [comment]
Did you add the correct native dependencies?

**Comment by demkom58** [comment]
I have used
```
    implementation group: 'it.tdlight', name: 'tdlib-java', version: "1.7.6.3"
    implementation group: 'it.tdlight', name: 'tdlib-natives-windows-amd64', version: "3.3.65"
```
And tested it on Windows 64bit, so I think yes. Everything else works correctly.

**Comment by Cavallium** [comment]
Did you execute Init.start() before?

**Comment by demkom58** [comment]
> Did you execute Init.start() before?
Yes.

**Comment by Cavallium** [comment]
That's very strange, can you execute the example in the readme and tell me if it works?

**Comment by demkom58** [comment]
Oh, sorry, I realized my mistake...
Thank you for your time. <3
