### ISSUE TITLE
Cannot create a Secret chat

### ISSUE THREAD

**Issue by dariocode** [tdlight-team/tdlight-java#5]
I'm trying to make a secret chat without success.

I'm executing the command
`new TdApi.CreateNewSecretChat(userId)`

but into the log with verbosity 5 is not logged anything.

**Comment by dariocode** [comment]
After a while, the chat was be built!
Is there a limit on a number of secret chat that can be built?

**Comment by Cavallium** [comment]
I don't know, this is an issue that you must ask to tdlib developers. This is a simple wrapper of their functions.
