### ISSUE TITLE
Can't find analogue of https://core.telegram.org/type/InputPeer

### ISSUE THREAD

**Issue by siarheul** [tdlight-team/tdlight-java#55]
I'm looking at the ways to send a message to direct (or private) chat to some user by userId
It seems InputPeer can help with
But I cannot find such an entity in documentation https://tdlight-team.github.io/tdlight-docs/tdlight.api/module-summary.html

How to send a direct message without this class?
Thank you!

**Comment by Cavallium** [comment]
core.telegram.org is the documentation of MTProto, not TDLib. TDLib works in a completely different way.

To send a message to a chat you must use SendMessage.

https://tdlight-team.github.io/tdlight-docs/tdlight.api/it/tdlight/jni/TdApi.SendMessage.html
