### ISSUE TITLE
JavaDoc grid overflows the browser maximum CSS grid limit, hiding some subclasses in TdApi class

### ISSUE THREAD

**Issue by HuMzan** [tdlight-team/tdlight-java#56]
No longer in the list
https://tdlight-team.github.io/tdlight-docs/tdlight.api/it/tdlight/jni/package-summary.html
Can only be found by searching

**Comment by Cavallium** [comment]
Unfortunately it's a client-side limitation.
CSS allows the browser to limit the maximum number of rows in a grid:

https://drafts.csswg.org/css-grid-2/#overlarge-grids

**Comment by Cavallium** [comment]
I updated the documentation links to link to the class tree, that seems unaffected by this bug.

https://tdlight-team.github.io

**Comment by cavallium** [comment]
Fixed
