### ISSUE TITLE
tdlight-java Unable to download it.unimi.dsi:fastutil 8.5.6.  Repository reported an 400 error

### ISSUE THREAD

**Issue by HuMzan** [tdlight-team/tdlight-java#58]
![屏幕截图 2021-11-08 170229](https://user-images.githubusercontent.com/24567958/140713543-6d4e1a1a-469d-4c6f-975c-7262434622f7.png)

In the local project, I successfully downloaded it.unimi.dsi:fastutil 8.5.6

Cause of occurrence:
Could not find artifact it.unimi.dsi:fastutil:jar:8.5.6 in mchv-release (https://mvn.mchv.eu/repository/mchv)

**Comment by gam2046** [comment]
same issue

```
Execution failed for task ':compileKotlin'.
> Error while evaluating property 'filteredArgumentsMap' of task ':compileKotlin'
   > Could not resolve all files for configuration ':compileClasspath'.
      > Could not resolve it.tdlight:tdlight-java:2.7.9.2.
        Required by:
            project :
         > Could not resolve it.tdlight:tdlight-java:2.7.9.2.
            > Could not parse POM https://mvn.mchv.eu/repository/mchv/it/tdlight/tdlight-java/2.7.9.2/tdlight-java-2.7.9.2.pom
               > Could not resolve it.tdlight:tdlight-java-parent:2.7.9.2.
                  > Could not resolve it.tdlight:tdlight-java-parent:2.7.9.2.
                     > inconsistent module metadata found. Descriptor: it.tdlight:tdlight-java-parent:1.0.0.0-SNAPSHOT Errors: bad version: expected='2.7.9.2' found='1.0.0.0-SNAPSHOT'

```

**Comment by cavallium** [comment]
@HuMzan please can you give me the full log?

**Comment by cavallium** [comment]
> same issue
> 
> ```
> Execution failed for task ':compileKotlin'.
> > Error while evaluating property 'filteredArgumentsMap' of task ':compileKotlin'
>    > Could not resolve all files for configuration ':compileClasspath'.
>       > Could not resolve it.tdlight:tdlight-java:2.7.9.2.
>         Required by:
>             project :
>          > Could not resolve it.tdlight:tdlight-java:2.7.9.2.
>             > Could not parse POM https://mvn.mchv.eu/repository/mchv/it/tdlight/tdlight-java/2.7.9.2/tdlight-java-2.7.9.2.pom
>                > Could not resolve it.tdlight:tdlight-java-parent:2.7.9.2.
>                   > Could not resolve it.tdlight:tdlight-java-parent:2.7.9.2.
>                      > inconsistent module metadata found. Descriptor: it.tdlight:tdlight-java-parent:1.0.0.0-SNAPSHOT Errors: bad version: expected='2.7.9.2' found='1.0.0.0-SNAPSHOT'
> ```

This is not the same issue

**Comment by HuMzan** [comment]
> > same issue
> > ```
> > Execution failed for task ':compileKotlin'.
> > > Error while evaluating property 'filteredArgumentsMap' of task ':compileKotlin'
> >    > Could not resolve all files for configuration ':compileClasspath'.
> >       > Could not resolve it.tdlight:tdlight-java:2.7.9.2.
> >         Required by:
> >             project :
> >          > Could not resolve it.tdlight:tdlight-java:2.7.9.2.
> >             > Could not parse POM https://mvn.mchv.eu/repository/mchv/it/tdlight/tdlight-java/2.7.9.2/tdlight-java-2.7.9.2.pom
> >                > Could not resolve it.tdlight:tdlight-java-parent:2.7.9.2.
> >                   > Could not resolve it.tdlight:tdlight-java-parent:2.7.9.2.
> >                      > inconsistent module metadata found. Descriptor: it.tdlight:tdlight-java-parent:1.0.0.0-SNAPSHOT Errors: bad version: expected='2.7.9.2' found='1.0.0.0-SNAPSHOT'
> > ```
> 
> This is not the same issue

This is the complete log. When I compile it, I can't download it when I download it with Maven：
Could not find artifact it.unimi.dsi:fastutil:jar:8.5.6 in mchv-release (https://mvn.mchv.eu/repository/mchv)

![屏幕截图 2021-11-08 170229](https://user-images.githubusercontent.com/24567958/140968725-fb1fa62e-a0ea-447d-a8d0-65d0929d029b.png)

**Comment by cavallium** [comment]
> > > same issue
> > > ```
> > > Execution failed for task ':compileKotlin'.
> > > > Error while evaluating property 'filteredArgumentsMap' of task ':compileKotlin'
> > >    > Could not resolve all files for configuration ':compileClasspath'.
> > >       > Could not resolve it.tdlight:tdlight-java:2.7.9.2.
> > >         Required by:
> > >             project :
> > >          > Could not resolve it.tdlight:tdlight-java:2.7.9.2.
> > >             > Could not parse POM https://mvn.mchv.eu/repository/mchv/it/tdlight/tdlight-java/2.7.9.2/tdlight-java-2.7.9.2.pom
> > >                > Could not resolve it.tdlight:tdlight-java-parent:2.7.9.2.
> > >                   > Could not resolve it.tdlight:tdlight-java-parent:2.7.9.2.
> > >                      > inconsistent module metadata found. Descriptor: it.tdlight:tdlight-java-parent:1.0.0.0-SNAPSHOT Errors: bad version: expected='2.7.9.2' found='1.0.0.0-SNAPSHOT'
> > > ```
> > 
> > 
> > This is not the same issue
> 
> This is the complete log. When I compile it, I can't download it when I download it with Maven： Could not find artifact it.unimi.dsi:fastutil:jar:8.5.6 in mchv-release (https://mvn.mchv.eu/repository/mchv)
> 
> ![QQ截图20211110005242](https://user-images.githubusercontent.com/24567958/140968784-2429a33e-d4f4-4c44-b767-e4dd9613aefd.png)

Fastutil is not in mchv repository. It's in maven central repository.

**Comment by HuMzan** [comment]
I can't reproduce this compilation error again
But when I right-click to download again, the scene above will appear
![屏幕截图 2021-11-10 005903](https://user-images.githubusercontent.com/24567958/140969806-97d60b92-7ae2-4dee-88fb-0db0480ffb13.png)

**Comment by HuMzan** [comment]
> > > > 同样的问题
> > > > ```
> > > > Execution failed for task ':compileKotlin'.
> > > > > Error while evaluating property 'filteredArgumentsMap' of task ':compileKotlin'
> > > >    > Could not resolve all files for configuration ':compileClasspath'.
> > > >       > Could not resolve it.tdlight:tdlight-java:2.7.9.2.
> > > >         Required by:
> > > >             project :
> > > >          > Could not resolve it.tdlight:tdlight-java:2.7.9.2.
> > > >             > Could not parse POM https://mvn.mchv.eu/repository/mchv/it/tdlight/tdlight-java/2.7.9.2/tdlight-java-2.7.9.2.pom
> > > >                > Could not resolve it.tdlight:tdlight-java-parent:2.7.9.2.
> > > >                   > Could not resolve it.tdlight:tdlight-java-parent:2.7.9.2.
> > > >                      > inconsistent module metadata found. Descriptor: it.tdlight:tdlight-java-parent:1.0.0.0-SNAPSHOT Errors: bad version: expected='2.7.9.2' found='1.0.0.0-SNAPSHOT'
> > > > ```
> > > 
> > > 
> > > 这不是同一个问题
> > 
> > 
> > 这是完整的日志。我编译的时候用Maven下载的时候下载不了：Could not find artifact it.unimi.dsi:fastutil:jar:8.5.6 in mchv-release ( [https://mvn.mchv.eu/存储库/ mchv](https://mvn.mchv.eu/repository/mchv) )
> > ![QQ截图20211110005242](https://user-images.githubusercontent.com/24567958/140968784-2429a33e-d4f4-4c44-b767-e4dd9613aefd.png)
> 
> Fastutil 不在 mchv 存储库中。它在 Maven 中央存储库中。
I deleted the local library and reappeared it again
![屏幕截图 2021-11-10 010534](https://user-images.githubusercontent.com/24567958/140970803-55450081-ea50-466b-a3c2-23e9f7301a84.png)

**Comment by cavallium** [comment]
You should download it from the maven central repository.

**Comment by cavallium** [comment]
<repository>
    <id>central</id>
    <name>Maven Central</name>
    <layout>default</layout>
    <url>https://repo1.maven.org/maven2</url>
    <snapshots>
    <enabled>false</enabled>
    </snapshots>
  </repository>

**Comment by HuMzan** [comment]
> ```
>   <存储库>
>     < id >中央</ id >
>     <名称>Maven 中心</名称>
>     <布局>默认</布局>
>     < url >https://repo1.maven.org/maven2</ url >
>     <快照>
>     <启用>假</启用>
>     </快照>
>   </存储库>
> ```
Yes, I tried, but I couldn't download
I can download it with my browser
![屏幕截图 2021-11-10 011537](https://user-images.githubusercontent.com/24567958/140972415-9768c15c-cf1d-4966-b5af-f1ad97324278.png)

**Comment by HuMzan** [comment]
I wonder why the download speed here is slow.....

**Comment by HuMzan** [comment]
> ```
>   <存储库>
>     < id >中央</ id >
>     <名称>Maven 中心</名称>
>     <布局>默认</布局>
>     < url >https://repo1.maven.org/maven2</ url >
>     <快照>
>     <启用>假</启用>
>     </快照>
>   </存储库>
> ```

Thank you for your answer. It should be my local environmental impact,I try to solve
