### ISSUE TITLE
I observed that i.t.c.TelegramClient.createAndRegisterClient:162 seems to use a global lock?

### ISSUE THREAD

**Issue by HuMzan** [tdlight-team/tdlight-java#59]
I want to know if this global lock is not necessary?Or become an Client object lock

Because when I start multiple clients, I always need to queue

**Comment by cavallium** [comment]
I don't see any lock

**Comment by HuMzan** [comment]
> 我没有看到任何锁

For example, account A adds Thread.sleep(50000) to TdApi.AuthorizationStateWaitEncryptionKey; other accounts must wait for account A to end its sleep before proceeding.

**Comment by HuMzan** [comment]
> 我没有看到任何锁

Maybe it’s not a lock, it’s a queue

**Comment by cavallium** [comment]
**You must not lock or wait inside asynchronous callbacks!**

**Comment by HuMzan** [comment]
> **您不能在异步回调中锁定或等待！**



> **您不能在点击屏幕中锁定或等待！**

But I use an account to occupy a thread, I think it will not affect the other?

**Comment by HuMzan** [comment]
> **You must not lock or wait inside asynchronous callbacks!**

But I use an account to occupy a thread, I think it will not affect the other
What I understand is that every client should have an UpdatesHandler asynchronous callback,Do you think I am wrong?

**Comment by HuMzan** [comment]
> **You must not lock or wait inside asynchronous callbacks!**

Because I occupies a thread for each account to test sleep.
So what do you mean is that when I dormant one of them, because not receive the callback, the login authorization of other accounts will be blocked

**Comment by cavallium** [comment]
You should never block inside a tdlight-java callback.
If you need to block/wait, you must do that into a separate thread.

**Comment by HuMzan** [comment]
> You should never block inside a tdlight-java callback. If you need to block/wait, you must do that into a separate thread.

I understand. What bothers me in fact is that when staff A is logging in, staff B often cannot perform operations such as entering passwords normally.

**Comment by cavallium** [comment]
> > You should never block inside a tdlight-java callback. If you need to block/wait, you must do that into a separate thread.
> 
> I understand. What bothers me in fact is that when staff A is logging in, staff B often cannot perform operations such as entering passwords normally.
> 
> I need to work hard to figure out how to solve it, thank you for your answer

If you don't like how SimpleClient handles the login events, you can override the behavior using client.setClientInteraction(_your custom ClientInteraction implementation_)
