### ISSUE TITLE
Using TerminateAllOtherSessions will cause your account session to log out

### ISSUE THREAD

**Issue by HuMzan** [tdlight-team/tdlight-java#60]
When my account executes the following code, maybe it is the second time or after the third login, I will receive the TdApi.AuthorizationStateLoggingOut notification

Need to perform TdApi.AuthorizationStateWaitCode operation again

I paid several accounts for this because I can’t receive text messages again

`
this.clientBase.client.send(new TdApi.TerminateAllOtherSessions( ), this::onResult);
`

**Comment by HuMzan** [comment]
Do I still have a chance to restore my account?

**Comment by cavallium** [comment]
TerminateAllOtherSessions does exactly what it says in the documentation: "Terminates all other sessions of the current user."
You must login again using your phone number.

**Comment by HuMzan** [comment]
> TerminateAllOtherSessions does exactly what it says in the documentation: "Terminates all other sessions of the current user." You must login again using your phone number.


My understanding is all sessions of other devices, not all sessions
I was thinking that if it appeared the second time I logged in, I think I would immediately realize that I misunderstood the description of the file

**Comment by cavallium** [comment]
It kills other sessions.
You probably logged out or deleted the session on tdlight. I tried and it works correctly.
