### ISSUE TITLE
Can't find dependent libraries

### ISSUE THREAD

**Issue by klpanda** [tdlight-team/tdlight-java#62]
![image](https://user-images.githubusercontent.com/10952277/144412731-15560290-c0dc-4d4c-994a-b4238cea58b3.png)

**Comment by cavallium** [comment]
You must have Microsoft Visual C++ installed
https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

**Comment by klpanda** [comment]
> You must have Microsoft Visual C++ installed https://aka.ms/vs/17/release/vc_redist.x64.exe

https://aka.ms/vs/17/release/vc_redist.x64.exe
HTTP ERROR 404


![image](https://user-images.githubusercontent.com/10952277/144536475-8964a97f-9e79-4f53-8181-be395a32021b.png)

**Comment by klpanda** [comment]
3Q
