### ISSUE TITLE
Internal client sending array of 99 null objects every time a single event is sent

### ISSUE THREAD

**Issue by dshaver1** [tdlight-team/tdlight-java#64]
I just updated to the latest version of tdlight and found that the internal client is now sending me 99 null objects for every singular update event. It seems somewhere along the way you're instantiating an array with 100 size. For now I can just do a null check on my end, but it seems like a bug. The previous version I was using did not exhibit this behavior.

Looking into this further, I believe the bug was introduced with the commit https://github.com/tdlight-team/tdlight-java/commit/6558bd9ba94936abf8f3cdda893a079f43615059

The `ReactiveInternalClient` avoids this issue by only calling `handleEvent` based on the `arrayOffset` and `arrayLength` values passed in:
```
		for (int i = arrayOffset; i < arrayOffset + arrayLength; i++) {
			handleEvent(eventIds[i], events[i]);
		}
```

But the `InternalClient` passes the entire list of 100 (mostly null) updates to the update handler:

```
updatesHandler.getUpdatesHandler().onUpdates(eventsToFilter);
```

If I understand this correctly, you may be able to solve this issue by instantiating the `eventsToFilter` as a copy of `events` but limited to the desired range with:

```
ObjectArrayList<TdApi.Object> eventsToFilter = new ObjectArrayList<>(Arrays.copyOfRange(events, 0, arrayLength));
```

For now I will update my implementation of `UpdatesHandler` to filter nulls, but I'd prefer to avoid having this method needlessly called 99 times for every 1 legitimate update event.

**Comment by cavallium** [comment]
When I optimized the handler of InternalClient I completely forgot to also update the data sent to updatesHandler.

**Comment by cavallium** [comment]
I'll release the fixed version when the CI deploys the next TDLib update (about 4 hours).
