### ISSUE TITLE
Users need to be re-authenticated during server-side multi-node deployment

### ISSUE THREAD

**Issue by winslow0810** [tdlight-team/tdlight-java#67]
I deployed a multi-node java server. When a user reconnects from one node to another, the user needs to re-authenticate because the user's session file is on the previous server。Can this problem be solved? Or how can the user's session file be shared among multiple server nodes?  I have been stuck here for a week, hope you guys can help me, thanks

**Comment by cavallium** [comment]
This is not an issue, you need to reauthenticate
