### ISSUE TITLE
UpdateNewMessage event duplicates in UpdateDeleteMessages

### ISSUE THREAD

**Issue by Teramaks** [tdlight-team/tdlight-java#70]
![image](https://user-images.githubusercontent.com/49274571/149390672-c44975f2-ab99-4efd-ac44-f0fa6d5ba546.png)
![image](https://user-images.githubusercontent.com/49274571/149390799-331d6216-b4e7-49b9-ab0e-91d2acffdf6a.png)

**Comment by Teramaks** [comment]
All ids in messageIds array was't deleted, chat type is private

**Comment by cavallium** [comment]
Look at the [fromCache](https://tdlight-team.github.io/tdlight-docs/tdlight.api/it/tdlight/jni/TdApi.UpdateDeleteMessages.html#fromCache) and [isPermanent](https://tdlight-team.github.io/tdlight-docs/tdlight.api/it/tdlight/jni/TdApi.UpdateDeleteMessages.html#isPermanent) fields documentation in UpdateDeleteMessages
