### ISSUE TITLE
What are the reasons why the client cannot be closed for a long time?

### ISSUE THREAD

**Issue by HuMzan** [tdlight-team/tdlight-java#77]
When I execute new TdApi.Close() ,After receiving the TdApi.AuthorizationStateClosing notification, it takes a very long time to receive the TdApi.AuthorizationStateClosed

So I don't know if the unknown conditions are not met, resulting in a prolonged shutdown.

I want to kill a client quickly

![2022-01-24 140045](https://user-images.githubusercontent.com/24567958/150730083-087762c2-ee04-40d3-aff5-4490d455066b.png)

**Comment by cavallium** [comment]
Unfortunately this is a tdlib problem, not my wrapper's.
