### ISSUE TITLE
Downloaded MessageDocument are corrupted

### ISSUE THREAD

**Issue by dariocode** [tdlight-team/tdlight-java#8]
I'm trying to handling the TdApi.UpdateNewMessage.CONSTRUCTOR event, after the request to download a document message (it is a zip file).
The downloaded document results as corrupted file.
I requested to download the MessageDocument catching the TdApi.UpdateNewMessage event filtering the message content of type TdApi.MessageDocument

```
TdApi.UpdateNewMessage.CONSTRUCTOR: 
TdApi.UpdateNewMessage updateNewMessage = (TdApi.UpdateNewMessage) object;
if (updateNewMessage.message.content instanceof TdApi.MessageDocument) {
int fileId = ((TdApi.MessageDocument) updateNewMessage.message.content).document.document.id;
int fileSize = 0;
int priority = 10;
new TdApi.DownloadFile(fileId, priority, 0, fileSize, false),
        updatesDocumentHandler,
        new ErrorCallback() {
          @Override
          public void onError(Response error) {
            log.error(error.getObject().toString());
          }
        });
}


// then when document is downloaded I catch the file path: 
case TdApi.UpdateFile.CONSTRUCTOR:
          // global on result
          TdApi.UpdateFile updateFile = (TdApi.UpdateFile) object;
if ((updateFile).file.local.isDownloadingCompleted) {
          String filePath = updateFile.file.local.path;
.... 
}

```

I look the downloaded file inside the folder named "secret" of the database directory. I'm using a secret chat. 

Note. When I try to download files with a size less of 64kb the zip file download is not corrupted!

**Comment by Cavallium** [comment]
Try with the version with tdlib binaries: https://github.com/tdlight-team/tdlight-java/releases/tag/v3.168.13-tdlib

Tell me if the problem is present also in that variant.

**Comment by dariocode** [comment]
I'm already using that version
	<dependency>
			<groupId>it.tdlight</groupId>
			<artifactId>tdlight-java</artifactId>
			<version>3.168.13</version>
		</dependency>

The problem is present in this version.

**Comment by Cavallium** [comment]
No, I said that you should try:
```xml
	         <dependency>
			<groupId>it.tdlight</groupId>
			<artifactId>tdlib-java</artifactId>
			<version>3.168.13</version>
		</dependency>
```

**Comment by Cavallium** [comment]
By the way I use your version in my bots and I don't have this problems downloading and uploading files

**Comment by dariocode** [comment]
The tdlib-java and tdlight-java libraries seem ok. 

The problem is that a file named as "suffix:xxxxx" sent using an old version of android tdlib reach the destination as corrupted file. This happens also using the official Telegram client. 

This current issue can be closed. Thanks
