### ISSUE TITLE
Download File 

### ISSUE THREAD

**Issue by ctaity** [tdlight-team/tdlight-java#82]
Hi, need help, I like to know if is possible to use the unique id or the id from a remote file (photo or video) in another telegram client to download the file in this client. 
I have a telegram client listening media message and save the ids into a database, and in another server, I have another telegram client acting as a proxy, when I need a photo I make an HTTP request with the photo id this client downloads and streams photo via HTTP for example. is possible?

**Comment by cavallium** [comment]
No it's not possible. Telegram only allows to download files that have been seen by the client that you are using.
