### ISSUE TITLE
it.tdlight.tdlib.TdApi.Chat and org.drinkless.tdlib.TdApi.Chat are different

### ISSUE THREAD

**Issue by ashvydkyi** [tdlight-team/tdlight-java#9]
hey guys

How it is possible that TdApi class build with [official java example](https://github.com/tdlib/td/tree/master/example/java) is different from it.tdlight.tdlib.TdApi?
Right now I see differences in TdApi.Chat class where **chatList** and **order** fields are missing.

Regards, 

Anton

**Comment by Cavallium** [comment]
Probably the official example uses TDLib version 1.6.9, while our latest release still uses 1.6.8.
We are still upgrading our packages to 1.6.9

**Comment by ashvydkyi** [comment]
@Cavallium do you know when the upgrade will be completed? Days/Months?

**Comment by Cavallium** [comment]
We switched from travis to jenkins to build the library, currently we have finished converting the build script for linux-amd64 and linux-aarch64.
I almost finished preparing the windows build, so it may be completed today.

(From the next release onwards we will drop MacOS support because Apple don't allow to use its build tools outside Apple hardware)

**Comment by ashvydkyi** [comment]
@Cavallium which build tool are you referring to?

**Comment by Cavallium** [comment]
https://www.apple.com/legal/sla/docs/xcode.pdf

 _You may not alter the Apple Software or Services in any way in such copy, e.g., You are expressly prohibited from separately using the Apple SDKsor attempting to run any part of the Apple Software on non-Apple-branded hardware._

**Comment by ashvydkyi** [comment]
@Cavallium 
Right now I am running tdlight-java on MacBook Pro.
In case if you need to build the next release, using macOS, I can help with it.

**Comment by Cavallium** [comment]
I'm building the next version of tdlight. I've re-added support for macOS.

**Comment by Cavallium** [comment]
Also, in next version I changed some package names.

**Comment by Cavallium** [comment]
> hey guys
> 
> How it is possible that TdApi class build with [official java example](https://github.com/tdlib/td/tree/master/example/java) is different from it.tdlight.tdlib.TdApi?
> Right now I see differences in TdApi.Chat class where **chatList** and **order** fields are missing.
> 
> Regards,
> 
> Anton

With the latest version all the classes are equal.
