### ISSUE TITLE
mvn.mchv.eu is timeout

### ISSUE THREAD

**Issue by vyouzhis** [tdlight-team/tdlight-java#94]
`
curl https://mvn.mchv.eu/repository/mchv/org/java-websocket/Java-WebSocket/maven-metadata.xml
curl: (7) Failed connect to mvn.mchv.eu:443; Connection timed out
`

`

dig mvn.mchv.eu

; <<>> DiG 9.11.4-P2-RedHat-9.11.4-9.P2.el7 <<>> mvn.mchv.eu
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 43834
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;mvn.mchv.eu.			IN	A

;; ANSWER SECTION:
mvn.mchv.eu.		300	IN	CNAME	local.warp.ovh.
local.warp.ovh.		60	IN	CNAME	local.cavallium.it.
local.cavallium.it.	60	IN	A	94.36.87.186

;; Query time: 1022 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Thu May 26 09:19:53 CST 2022
;; MSG SIZE  rcvd: 116

`

**Comment by cavallium** [comment]
Sorry the server had a problem tonight, I'm rebooting it now.
